### ISSUE TITLE
MSVC Debug Assertion Failed:  cannot subtract incompatible string_view iterators

### ISSUE THREAD

**Issue by dbkkos** [zaalang/zacc#5]
File: builtins.cpp 
Call: make_function
Line: 136  
bug: tok.text.end() - beg

**Comment by pniekamp** [comment]
Right. I keep thinking string_view iterators are char pointers :(

I've attempted to fix up that one and another couple I saw. However, I don't have a llvm debug compile at hand, so testing is a little weak. I'll start the process and see how it goes...
